export default {
    SET_NAME: "SET_NEW_PALETTE_NAME",
    SET_EMOJI: "SET_NEW_PALETTE_EMOJI",
    ADD_COLOR: "ADD_NEW_PALETTE_COLOR",
    REMOVE_COLOR: "REMOVE_NEW_PALETTE_COLOR",
    CLEAR: "CLEAR_NEW_PALETTE",
    SORT: "SORT_NEW_PALETTE_COLORS",
};
